version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
      - dependency-name: 'kuroshiro'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
